# Generated by Django 2.0.1 on 2018-01-11 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20180111_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoAusentismo',
            fields=[
                ('idPermisoAusentismo', models.AutoField(primary_key=True, serialize=False)),
                ('mes_evento', models.SmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=1)),
                ('tipo_evento', models.SmallIntegerField(choices=[(1, 'A.T'), (2, 'E.L'), (3, 'A.C-E.G')], default=1)),
                ('periodoIncapacidadInicial', models.DateField()),
                ('periodoIncapacidadFinal', models.DateField()),
                ('prorroga', models.SmallIntegerField()),
                ('totalDiasIncapacidad', models.SmallIntegerField()),
                ('diasCargados', models.SmallIntegerField()),
                ('codigoDiagnostico', models.CharField(max_length=4)),
                ('observaciones', models.CharField(max_length=500)),
                ('idTrabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Trabajadores')),
            ],
        ),
    ]
