# Generated by Django 2.0.1 on 2018-01-15 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso_ausentismo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoausentismo',
            name='diasCargados',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='permisoausentismo',
            name='periodoIncapacidadFinal',
            field=models.DateField(default=datetime.date(2018, 1, 15)),
        ),
        migrations.AlterField(
            model_name='permisoausentismo',
            name='periodoIncapacidadInicial',
            field=models.DateField(default=datetime.date(2018, 1, 15)),
        ),
        migrations.AlterField(
            model_name='permisoausentismo',
            name='prorroga',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='permisoausentismo',
            name='totalDiasIncapacidad',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
