# Generated by Django 2.0.1 on 2018-01-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso_ausentismo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoausentismo',
            name='codigoDiagnostico',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='permisoausentismo',
            name='tipo_evento',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'A.T Accidente de trabajo'), (2, 'E.L Enfermedad laboral'), (3, 'A.C-E.G Enfermedad general')], default=1),
        ),
    ]
