# Generated by Django 2.0.1 on 2018-01-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso_ausentismo', '0002_auto_20180126_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoausentismo',
            name='observaciones',
            field=models.CharField(blank=True, default='Sin observaciones.', max_length=500, null=True),
        ),
    ]
