# Generated by Django 2.0.1 on 2018-01-15 12:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('permiso_ausentismo', '0002_auto_20180115_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoausentismo',
            name='periodoIncapacidadFinal',
            field=models.DateField(default=datetime.datetime(2018, 1, 15, 12, 52, 9, 191702, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisoausentismo',
            name='periodoIncapacidadInicial',
            field=models.DateField(default=datetime.datetime(2018, 1, 15, 12, 52, 9, 191665, tzinfo=utc)),
        ),
    ]
