# Generated by Django 2.0.1 on 2018-01-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso_ausentismo', '0003_auto_20180126_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoausentismo',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
