# Generated by Django 2.0.1 on 2018-01-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso_ausentismo', '0003_auto_20180130_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoausentismo',
            name='tipo_evento',
            field=models.SmallIntegerField(choices=[(1, 'A.T Accidente de trabajo'), (2, 'E.L Enfermedad laboral'), (3, 'A.C-E.G Enfermedad general'), (5, 'O.E Otro tipo de evento')], default=1),
        ),
    ]
