# Generated by Django 2.0.1 on 2018-01-15 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('permiso_ausentismo', '0003_auto_20180115_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoausentismo',
            name='periodoIncapacidadFinal',
            field=models.DateField(default=datetime.datetime(2018, 1, 15, 12, 55, 47, 929903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='permisoausentismo',
            name='periodoIncapacidadInicial',
            field=models.DateField(default=datetime.datetime(2018, 1, 15, 12, 55, 47, 929865, tzinfo=utc)),
        ),
    ]
