# Generated by Django 2.0.1 on 2018-01-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso_ausentismo', '0004_auto_20180115_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoausentismo',
            name='periodoIncapacidadFinal',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='permisoausentismo',
            name='periodoIncapacidadInicial',
            field=models.DateField(),
        ),
    ]
