# Generated by Django 2.0.1 on 2018-02-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso_ausentismo', '0004_auto_20180130_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoausentismo',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
