# Generated by Django 2.0.1 on 2018-01-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso_ausentismo', '0005_auto_20180115_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoausentismo',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
