# Generated by Django 2.0.1 on 2018-02-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso_ausentismo', '0005_auto_20180201_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoausentismo',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
