# Generated by Django 2.0.1 on 2018-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso_ausentismo', '0009_auto_20180201_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoausentismo',
            name='horaFinal',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permisoausentismo',
            name='horaInicial',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
