# Generated by Django 2.0.1 on 2018-02-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permiso_ausentismo', '0010_auto_20180202_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisoausentismo',
            name='mes_evento',
        ),
    ]
