# Generated by Django 2.0 on 2018-01-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_IO',
            fields=[
                ('idHistorial', models.AutoField(primary_key=True, serialize=False)),
                ('accion_jornada', models.CharField(choices=[('EN', 'Entrada'), ('DYI', 'Inicio Desayuno'), ('ALI', 'Inicio Almuerzo'), ('PAI', 'Inicio Pausas Activas'), ('DCI', 'Inicio Descanso'), ('SA', 'Salida'), ('DYF', 'Fin Desayuno'), ('ALF', 'Fin Almuerzo'), ('PAF', 'Fin Pausas Activas'), ('DCF', 'Fin Descanso')], default='EN', max_length=3)),
                ('accion_jornada_hora', models.CharField(choices=[('HEN', 'Hora Entrada'), ('HDYI', 'Hora Inicio Desayuno'), ('HALI', 'Hora Inicio Almuerzo'), ('HPAI', 'Hora Inicio Pausas Activas'), ('HDCI', 'Hora Inicio Descanso'), ('HSA', 'Hora Salida'), ('HDYF', 'Hora Fin Desayuno'), ('HALF', 'Hora Fin Almuerzo'), ('HPAF', 'Hora Fin Pausas Activas'), ('HDCF', 'Hora Fin Descanso')], default='HEN', max_length=4)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=11)),
                ('fechaIngreso', models.DateField()),
                ('fechaNacimiento', models.DateField()),
                ('administrador', models.BooleanField()),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('CodigoBarras', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='historial_io',
            name='id_trabajadores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Trabajadores'),
        ),
    ]
