# Generated by Django 2.0 on 2017-12-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoBarras',
            fields=[
                ('idCodigoBarras', models.AutoField(primary_key=True, serialize=False)),
                ('CodigoBarras', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Historial_IO',
            fields=[
                ('idHistorial', models.AutoField(primary_key=True, serialize=False)),
                ('horaEntrada', models.DateTimeField()),
                ('horaSalida', models.DateTimeField()),
                ('horaDesayuno', models.DateTimeField()),
                ('horaDescanso', models.DateTimeField()),
                ('horaPausasActivas', models.DateTimeField()),
                ('horaAlmuerzo', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PermisoAusentismo',
            fields=[
                ('idPermisoAusentismo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSalida', models.DateTimeField()),
                ('totalHoras', models.SmallIntegerField()),
                ('motivo', models.SmallIntegerField()),
                ('observacion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=255, null=True)),
                ('cedula', models.CharField(max_length=11)),
                ('fechaIngreso', models.DateField()),
                ('fechaNacimiento', models.DateField()),
                ('edad', models.SmallIntegerField()),
                ('cargo', models.BooleanField()),
                ('telefono', models.CharField(max_length=10)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='permisoausentismo',
            name='idTrabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Trabajadores'),
        ),
        migrations.AddField(
            model_name='codigobarras',
            name='idTrabajadores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Trabajadores'),
        ),
    ]
