# Generated by Django 2.0 on 2018-01-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_IO',
            fields=[
                ('idHistorial', models.AutoField(primary_key=True, serialize=False)),
                ('accion_jornada', models.CharField(choices=[('EN', 'Entrada'), ('DYI', 'Inicio Desayuno'), ('ALI', 'Inicio Almuerzo'), ('PAI', 'Inicio Pausas Activas'), ('DCI', 'Inicio Descanso'), ('SA', 'Salida'), ('DYF', 'Fin Desayuno'), ('ALF', 'Fin Almuerzo'), ('PAF', 'Fin Pausas Activas'), ('DCF', 'Fin Descanso')], default='EN', max_length=3)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermisoAusentismo',
            fields=[
                ('idPermisoAusentismo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSalida', models.DateTimeField()),
                ('motivo', models.SmallIntegerField()),
                ('periodoIncapacidadInicial', models.DateField()),
                ('periodoIncapacidadFinal', models.DateField()),
                ('diasIncapacidad', models.SmallIntegerField()),
                ('codigoDiagnostico', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=11)),
                ('fechaIngreso', models.DateField()),
                ('fechaNacimiento', models.DateField()),
                ('edad', models.SmallIntegerField()),
                ('administrador', models.BooleanField()),
                ('telefono', models.CharField(blank=True, max_length=11, null=True)),
                ('CodigoBarras', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='permisoausentismo',
            name='idTrabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Trabajadores'),
        ),
        migrations.AddField(
            model_name='historial_io',
            name='id_trabajadores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Trabajadores'),
        ),
    ]
