# Generated by Django 2.0 on 2017-12-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajadores',
            old_name='area',
            new_name='administrador',
        ),
    ]
