# Generated by Django 2.0 on 2018-01-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_io',
            name='accion_jornada',
            field=models.CharField(choices=[('EN', 'Entrada'), ('DCF', 'Fin Descanso'), ('DYI', 'Inicio Desayuno'), ('DYF', 'Fin Desayuno'), ('DCI', 'Inicio Descanso'), ('SA', 'Salida'), ('PAI', 'Inicio Pausas Activas'), ('PAF', 'Fin Pausas Activas'), ('ALI', 'Inicio Almuerzo'), ('ALF', 'Fin Almuerzo')], default='EN', max_length=3),
        ),
    ]
