# Generated by Django 2.0 on 2018-01-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_io',
            name='accion_jornada_hora',
            field=models.CharField(choices=[('HEN', 'Hora Entrada'), ('HDYI', 'Hora Inicio Desayuno'), ('HALI', 'Hora Inicio Almuerzo'), ('HPAI', 'Hora Inicio Pausas Activas'), ('HDCI', 'Hora Inicio Descanso'), ('HSA', 'Hora Salida'), ('HDYF', 'Hora Fin Desayuno'), ('HALF', 'Hora Fin Almuerzo'), ('HPAF', 'Hora Fin Pausas Activas'), ('HDCF', 'Hora Fin Descanso')], default='HEN', max_length=4),
        ),
    ]
