# Generated by Django 2.0 on 2018-01-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_io',
            name='hora',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='nombres',
            field=models.CharField(default=10, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='telefono',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
