# Generated by Django 2.0 on 2018-02-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dias_festivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('festivos', models.DateField()),
            ],
        ),
    ]
