# Generated by Django 2.0 on 2017-12-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoDeAusentismo',
            fields=[
                ('idPermisoAusentismo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSalida', models.DateTimeField()),
                ('motivo', models.SmallIntegerField()),
                ('periodoIncapacidadInicial', models.DateField()),
                ('periodoIncapacidadFinal', models.DateField()),
                ('diasIncapacidad', models.SmallIntegerField()),
                ('codigoDiagnostico', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=500)),
                ('idTrabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Trabajadores')),
            ],
        ),
    ]
