# Generated by Django 2.0 on 2017-12-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='telefono',
            field=models.CharField(max_length=11),
        ),
    ]
