# Generated by Django 2.0 on 2017-12-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_permisodeausentismo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisodeausentismo',
            name='idTrabajador',
        ),
        migrations.DeleteModel(
            name='PermisoDeAusentismo',
        ),
    ]
