# Generated by Django 2.0 on 2018-01-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180103_1708'),
        ('main', '0002_auto_20180104_0942'),
    ]

    operations = [
    ]
