# Generated by Django 2.0 on 2017-12-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171221_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajadores',
            name='foto',
        ),
    ]
