# Generated by Django 2.0 on 2018-01-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_20180104_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_io',
            name='accion_jornada',
            field=models.CharField(choices=[('EN', 'Entrada'), ('DYI', 'Inicio Desayuno'), ('ALI', 'Inicio Almuerzo'), ('PAI', 'Inicio Pausas Activas'), ('DCI', 'Inicio Descanso'), ('SA', 'Salida'), ('DYF', 'Fin Desayuno'), ('ALF', 'Fin Almuerzo'), ('PAF', 'Fin Pausas Activas'), ('DCF', 'Fin Descanso')], default='EN', max_length=3),
        ),
    ]
