# Generated by Django 2.0 on 2017-12-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_trabajadores_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadores',
            name='foto',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
