# Generated by Django 2.0 on 2017-12-27 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171222_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_io',
            name='id_trabajadores',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='main.Trabajadores'),
            preserve_default=False,
        ),
    ]
