# Generated by Django 2.0 on 2017-12-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171222_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_io',
            name='horaEntrada',
            field=models.CharField(default='171228091349', max_length=12, unique=True),
        ),
    ]
