# Generated by Django 2.0 on 2017-12-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_historial_io_id_trabajadores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial_io',
            old_name='horaAlmuerzo',
            new_name='hora',
        ),
        migrations.RemoveField(
            model_name='historial_io',
            name='horaDesayuno',
        ),
        migrations.RemoveField(
            model_name='historial_io',
            name='horaDescanso',
        ),
        migrations.RemoveField(
            model_name='historial_io',
            name='horaEntrada',
        ),
        migrations.RemoveField(
            model_name='historial_io',
            name='horaPausasActivas',
        ),
        migrations.RemoveField(
            model_name='historial_io',
            name='horaSalida',
        ),
    ]
