# Generated by Django 2.0 on 2017-12-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171228_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_io',
            name='horaEntrada',
            field=models.CharField(default='17-12-28-09-18-34', editable=False, max_length=120),
        ),
    ]
