# Generated by Django 2.0 on 2017-12-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171228_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_io',
            name='horaEntrada',
            field=models.CharField(default='17-12-28-09-50-48', max_length=120),
        ),
    ]
