# Generated by Django 2.0 on 2017-12-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171228_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_io',
            name='accion_jornada',
            field=models.CharField(choices=[('EN', 'Entrada'), ('SA', 'Salida'), ('DEYO', 'Desayuno'), ('DESC', 'Descanso'), ('PA', 'Pausas Activas'), ('AL', 'Almuerzo')], default='EN', max_length=2),
        ),
    ]
