# Generated by Django 2.0 on 2017-12-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_historial_io_accion_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_io',
            name='hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
