# Generated by Django 2.0 on 2017-12-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20171228_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_io',
            name='horaEntrada',
            field=models.DateTimeField(),
        ),
    ]
