# Generated by Django 2.0 on 2017-12-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20171228_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_io',
            name='accion_jornada',
            field=models.CharField(choices=[('EN', 'Entrada'), ('SA', 'Salida'), ('DY', 'Desayuno'), ('DC', 'Descanso'), ('PA', 'Pausas Activas'), ('AL', 'Almuerzo')], default='EN', max_length=2),
        ),
    ]
